apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo
  namespace: si
  labels:
    app: dotnetdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
      - name: dotnetdemo
        image: dockerregistry987.azurecr.io/dotnet:1.0
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: key